column_names:
- title
- body
data_path: data/nlbse_24_test.csv
logs_dir: logs/nlbse24-logs-fix
mem: 492000
model_name: mistralai/Mixtral-8x7B-Instruct-v0.1
ngpus: 4
prompts_path: data/nlbse_24_prompts.json
responses_dir: responses/nlbse24-responses-fix
target_column: label
template_path: templates/template.yaml
time: 0-20:00:00
